<a href="https://colab.research.google.com/github/Lukerabr/Colab/blob/main/Atividade_IA_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import sklearn
import pandas
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
from google.colab import drive

dadosWifi = pandas.read_csv('/content/drive/MyDrive/Colab Notebooks/Dados_WIFI.csv')                          

# describe me retorna média, desvio padrão, valor minimo e máximo.
#dadosWifi.describe()

# 'atributos' recebendo os atributos e 'classe' recebendo a classe (rótulo).
atributosWifi = dadosWifi[['1F80_Oi_Fibra_5G', '1F80_Oi_Fibra_2.4G', 'CLARO_2G46A5B9', 'VIVO-68F0']].values

# quarto com modem = 1, varanda fundo = 2, cozinha = 3, quarto mãe = 4, sala = 5, varanda frente = 6, quarto vô = 7, edicula fundo = 8, oficina = 9.
classeWifi = dadosWifi[['Classe']].values


#atributosWifi.mean(axis=0) #array([88.49019608, 86.80392157, 58.09803922, 45.66666667])
#atributosWifi.std(axis=0) #array([16.27023331, 12.61499203, 32.79422169, 32.33626427])

# normalização dos dados 
atributosWifinormalizados = (atributosWifi - atributosWifi.mean(axis=0)) / atributosWifi.std(axis=0)

#atributosWifinormalizados.mean(axis=0) #array([ 3.13474736e-16,  5.26811710e-16, -1.04491579e-16,  7.83686841e-17])
#atributosWifinormalizados.std(axis=0) #array([1., 1., 1., 1.])

# Separação dos conjuntos treino, validação e teste, 70%, 15% e 15%, respectivamente.

train_ratio = 0.70
validation_ratio = 0.15
test_ratio = 0.15

# separando treino com 70% do dataset total
x_train, x_test, y_train, y_test = train_test_split(atributosWifinormalizados, classeWifi, test_size=1 - train_ratio)

# separando 15% para validação e teste
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=test_ratio/(test_ratio + validation_ratio)) 

# print para conferência
#print(x_train, x_val, x_test)

model = KNeighborsClassifier(n_neighbors=3)
# knn 3 vizinhos array([4, 7, 3, 7, 5, 5, 2, 4])
# knn 4 vizinhos array([1, 4, 2, 2, 1, 5, 7, 8])
# knn 5 vizinhos array([3, 7, 7, 7, 1, 4, 3, 3])

model.fit(x_train, np.ravel(y_train))

predicao_modelo = model.predict(x_test)

print(accuracy_score(y_test, predicao_modelo))
print(confusion_matrix(y_test, predicao_modelo))  
print(classification_report(y_test, predicao_modelo))


0.625
[[1 2 0 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
              precision    recall  f1-score   support

           1       1.00      0.33      0.50         3
           2       0.00      0.00      0.00         0
           5       0.67      1.00      0.80         2
           7       0.00      0.00      0.00         1
           8       1.00      1.00      1.00         2

    accuracy                           0.62         8
   macro avg       0.53      0.47      0.46         8
weighted avg       0.79      0.62      0.64         8



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
